### ISSUE TITLE
Implement a channel between nodes without a central server?

### ISSUE THREAD

**Issue by andrew-kennedy** [ben-ng/gaggle#10]
I'd like to allow nodes to communicate without needing to use redis or sockets.io, is there a recommended way to do this in gaggle, assuming I have the IPs of the nodes?

**Comment by ben-ng** [comment]
I haven't written a channel like that yet, but it's totally doable.
1. Duplicate [an existing channel](https://github.com/ben-ng/gaggle/tree/master/channels) and name it `p2p-channel` or something like that.
2. Modify the options so that the user can specify what nodes are in the cluster.
3. Use `net.socket` [(docs)](https://nodejs.org/api/net.html#net_class_net_socket) or similar to send & receive messages.

**Comment by andrew-kennedy** [comment]
thank you! I just now noticed the channel-interface file. I'll look into it.

**Comment by andrew-kennedy** [comment]
I noticed something else, in the readme you use a channel with  `name: redis`, and  `redisName: foo`, but then later have a channel with `name: redis` and `channelName: foo`. Is there a reason for this distinction/naming convention? what's the difference between the channelName and the name?

**Comment by andrew-kennedy** [comment]
@ben-ng I'm sort of new to node.js programming, would the p2p channel effectively need to start a TCP server in the constructor so that each node has a server? And then in the _connect method there would be logic connecting to each node? I'm just a bit confused as to how the concept of a Channel maps to a bunch of nodes. Each example channel connects to one external service at the moment.

**Comment by ben-ng** [comment]
Yes, the channel would start a server and then connect to each node.

**Comment by ben-ng** [comment]
Closing in favor of #12
